FROM ubuntu:22.04
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Configure image
ARG PYTHON_VERSION=3.10
ARG DEBIAN_FRONTEND=noninteractive

# Install basic tools and Python
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    git-lfs \
    build-essential \
    wget \
    python${PYTHON_VERSION} \
    python${PYTHON_VERSION}-dev \
    python${PYTHON_VERSION}-venv \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /root/hsr_data_converter

# Setup Python: Create a symbolic link for easier access
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install uv (Fast Python package manager)
ENV PATH="/root/.local/bin:$PATH"
RUN wget -qO- https://astral.sh/uv/install.sh | sh

COPY src/ ./src/
COPY .python-version .
COPY pyproject.toml .
COPY uv.lock .
COPY README.md .

RUN GIT_LFS_SKIP_SMUDGE=1 uv sync --frozen --no-editable

# Save the current git information an environment variable
ARG GIT_HASH
ARG GIT_BRANCH
ARG GIT_URL
ARG GIT_TAG
ENV GIT_HASH=${GIT_HASH} \
    GIT_BRANCH=${GIT_BRANCH} \
    GIT_URL=${GIT_URL} \
    GIT_TAG=${GIT_TAG}

CMD ["/bin/bash"]
