from typing import Any

# Define constants for HSR
GRIPPER_OPEN_ACTION = 1
GRIPPER_CLOSE_ACTION = 0

# Mapping of servo feature names to RecordedTopics property names
SERVO_FEATURE_TO_TOPIC_PROPERTY = {
    "command.servo.position": "servo_states_command_position",
    "command.servo.velocity": "servo_states_command_velocity",
    "state.servo.motor_position": "servo_states_present_motor_shaft_position",
    "state.servo.driven_position": "servo_states_present_driven_shaft_position",
    "state.servo.velocity": "servo_states_present_velocity",
    "state.servo.temperature": "servo_states_present_temperature",
    "state.servo.effort": "servo_states_present_effort",
    "state.servo.current": "servo_states_present_current",
}

# Joint limits for HSR controllers (min, max)
# Based on /hsrb/arm_trajectory_controller/command, /hsrb/head_trajectory_controller/command,
# and /hsrb/gripper_trajectory_controller/command specifications
HSR_JOINT_LIMITS = {
    "arm_lift_joint": (0.0, 0.69),
    "arm_flex_joint": (-2.62, 0.0),
    "arm_roll_joint": (-2.09, 3.84),
    "wrist_flex_joint": (-1.92, 1.22),
    "wrist_roll_joint": (-1.92, 3.67),
    "hand_motor_joint": (-0.798, 1.24),
    "head_pan_joint": (-3.84, 1.75),
    "head_tilt_joint": (-1.57, 0.52),
}

# Define the features of the transformed dataset
hsr_features: dict[str, dict[str, Any]] = {
    "observation.image.head": {
        "dtype": "video",
        "shape": [480, 640, 3],
        "names": ["height", "width", "channel"],
        "info": {
            "video.fps": 10,
            "video.codec": "av1",
            "video.pix_fmt": "yuv420p",
            "video.is_depth_map": "false",
            "has_audio": "false",
        },
    },
    "observation.image.hand": {
        "dtype": "video",
        "shape": [480, 640, 3],
        "names": ["height", "width", "channel"],
        "info": {
            "video.fps": 10,
            "video.codec": "av1",
            "video.pix_fmt": "yuv420p",
            "video.is_depth_map": "false",
            "has_audio": "false",
        },
    },
    "observation.state": {
        "dtype": "float32",
        "shape": (8,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
        ],
    },
    "observation.wrist.wrench": {
        "dtype": "float32",
        "shape": (6,),
        "names": [
            "force_x",
            "force_y",
            "force_z",
            "torque_x",
            "torque_y",
            "torque_z",
        ],
        "description": "Wrist wrench data (force and torque) flattened",
    },
    "observation.end_effector_pose.absolute": {
        "shape": (6,),
        "dtype": "float32",
        "names": ["x", "y", "z", "roll", "pitch", "yaw"],
    },
    "observation.end_effector_pose.relative": {
        "shape": (6,),
        "dtype": "float32",
        "names": ["x", "y", "z", "roll", "pitch", "yaw"],
    },
    "action.absolute": {
        "dtype": "float32",
        "shape": (8,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
        ],
        "description": "absolute action for all joints without hand_motor_joint(gripper)",
    },
    "action.state_diff": {
        "dtype": "float32",
        "shape": (8,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
        ],
        "description": "difference between next and current observation state",
    },
    "action.relative": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_x",
            "base_y",
            "base_t",
        ],
        "description": "delta action for all joints and base without hand_motor_joint(gripper)",
    },
    "action.arm": {
        "dtype": "float32",
        "shape": (5,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
        ],
        "description": "absolute action for arm joints",
    },
    "action.gripper": {
        "dtype": "float32",
        "shape": (1,),
        "names": ["hand_motor_joint"],
        "description": "absolute action for gripper",
    },
    "action.head": {
        "dtype": "float32",
        "shape": (2,),
        "names": ["head_pan_joint", "head_tilt_joint"],
        "description": "absolute action for head joints",
    },
    "action.base": {
        "dtype": "float32",
        "shape": (3,),
        "names": ["base_x", "base_y", "base_t"],
        "description": "delta action for base",
    },
    # NOTE: servo features represent RAW motor control signals and states
    "command.servo.position": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_l_drive_wheel_joint",
            "base_r_drive_wheel_joint",
            "base_roll_joint",
        ],
        "description": "low level servo position command",
    },
    "command.servo.velocity": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_l_drive_wheel_joint",
            "base_r_drive_wheel_joint",
            "base_roll_joint",
        ],
        "description": "low level servo velocity command",
    },
    "state.servo.motor_position": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_l_drive_wheel_joint",
            "base_r_drive_wheel_joint",
            "base_roll_joint",
        ],
        "description": "motor position",
    },
    "state.servo.driven_position": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_l_drive_wheel_joint",
            "base_r_drive_wheel_joint",
            "base_roll_joint",
        ],
        "description": "driven position",
    },
    "state.servo.velocity": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_l_drive_wheel_joint",
            "base_r_drive_wheel_joint",
            "base_roll_joint",
        ],
        "description": "low level controller velocity",
    },
    "state.servo.temperature": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_l_drive_wheel_joint",
            "base_r_drive_wheel_joint",
            "base_roll_joint",
        ],
        "description": "servo temperature",
    },
    "state.servo.effort": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_l_drive_wheel_joint",
            "base_r_drive_wheel_joint",
            "base_roll_joint",
        ],
        "description": "low level controller effort",
    },
    "state.servo.current": {
        "dtype": "float32",
        "shape": (11,),
        "names": [
            "arm_lift_joint",
            "arm_flex_joint",
            "arm_roll_joint",
            "wrist_flex_joint",
            "wrist_roll_joint",
            "hand_motor_joint",
            "head_pan_joint",
            "head_tilt_joint",
            "base_l_drive_wheel_joint",
            "base_r_drive_wheel_joint",
            "base_roll_joint",
        ],
        "description": "low level controller current",
    },
    # fresh mask to indicate whether the action is a fresh action or paded former action
    "observation.image.head.is_fresh": {
        "dtype": "bool",
        "shape": (
            3,
            1,
            1,
        ),  # NOTE: need to be [3,1,1] to be compatible with lerobot assertion check `_assert_type_and_shape` in `compute_stats.py`
        "names": None,
    },
    "observation.image.hand.is_fresh": {
        "dtype": "bool",
        "shape": (
            3,
            1,
            1,
        ),  # NOTE: need to be [3,1,1] to be compatible with lerobot assertion check `_assert_type_and_shape` in `compute_stats.py`
        "names": None,
    },
    "observation.state.is_fresh": {
        "dtype": "bool",
        "shape": (8,),
        "names": None,
    },
    "action.absolute.is_fresh": {
        "dtype": "bool",
        "shape": (8,),
        "names": None,
    },
    "action.state_diff.is_fresh": {
        "dtype": "bool",
        "shape": (8,),
        "names": None,
    },
    "action.relative.is_fresh": {
        "dtype": "bool",
        "shape": (11,),
        "names": None,
    },
    "action.arm.is_fresh": {
        "dtype": "bool",
        "shape": (5,),
        "names": None,
    },
    "action.gripper.is_fresh": {
        "dtype": "bool",
        "shape": (1,),
        "names": None,
    },
    "action.head.is_fresh": {
        "dtype": "bool",
        "shape": (2,),
        "names": None,
    },
    "action.base.is_fresh": {
        "dtype": "bool",
        "shape": (3,),
        "names": None,
    },
    "episode_index": {
        "dtype": "int64",
        "shape": (1,),
        "names": None,
    },
    "frame_index": {
        "dtype": "int64",
        "shape": (1,),
        "names": None,
    },
    "timestamp": {
        "dtype": "float32",
        "shape": (1,),
        "names": None,
    },
    "next.done": {
        "dtype": "bool",
        "shape": (1,),
        "names": None,
    },
    "index": {
        "dtype": "int64",
        "shape": (1,),
        "names": None,
    },
    "short_horizon_task_index": {
        "dtype": "int64",
        "shape": (1,),
        "names": None,
    },
    "primitive_action_index": {
        "dtype": "int64",
        "shape": (1,),
        "names": None,
    },
    "success_primitive_action": {
        "dtype": "bool",
        "shape": (1,),
        "names": None,
    },
}
